// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALjyF9XaoPlwGGqaIwBDV_4PGk4x4mx5U',
    appId: '1:868993176639:web:2f45a092df04384dc9148a',
    messagingSenderId: '868993176639',
    projectId: 'ecom-app-5f2c6',
    authDomain: 'ecom-app-5f2c6.firebaseapp.com',
    storageBucket: 'ecom-app-5f2c6.appspot.com',
    measurementId: 'G-8J0BFKY0D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHLe-nN0YL31unIon4z-vyWWxx30b-V8I',
    appId: '1:868993176639:android:307726c64a9b7d4fc9148a',
    messagingSenderId: '868993176639',
    projectId: 'ecom-app-5f2c6',
    storageBucket: 'ecom-app-5f2c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiz4k6t1TnIJo4-Cx6dPSnXVRDzilprFs',
    appId: '1:868993176639:ios:14aa0a9708bfe05fc9148a',
    messagingSenderId: '868993176639',
    projectId: 'ecom-app-5f2c6',
    storageBucket: 'ecom-app-5f2c6.appspot.com',
    iosClientId: '868993176639-la48fup0p71srh4lj5re1lsbjg2s6oqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.eStoreCoorgle',
  );
}
